import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  mainView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 50,
    backgroundColor: '#9500eb',
    paddingHorizontal: 10,
  },
  headerEle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 50,
    backgroundColor: '#004bfa',
    paddingHorizontal: 10,
  },
  headerBok: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 50,
    backgroundColor: '#eb00e3',
    paddingHorizontal: 10,
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    alignSelf: 'center',
    color: '#fff',
    textShadowColor: 'black',
    textShadowRadius: 5,
    textShadowOffset: {
      width: 2,
      height: 2,
    },
  },
  back: {
    width: 30,
    height: 30,
    marginRight: 10,
    tintColor: '#fff',
  },
  category: {
    height: 35,
    width: 80,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 45 / 2,
    marginRight: 10,
  },
  textCategory: {
    fontWeight: 'bold',
  },
  list: {
    backgroundColor: '#fff',
    borderRadius: 20,
    elevation: 5,
    backgroundColor: 'white',
    flexDirection: 'row',
    margin: 10,
    padding: 10,
  },
  listProducts: {
    height: 160,
    width: 120,
    backgroundColor: '#fff',
    shadowColor: '#00000021',
    shadowOffset: {
      width: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    flexBasis: '47%',
  },
  viewProducts: {
    height: 40,
    paddingHorizontal: 16,
    borderTopLeftRadius: 1,
    borderTopRightRadius: 1,
  },
  image: {
    height: 150,
    width: 150,
    borderRadius: 10,
  },
  textList: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
  },
  iconContainer: {
    paddingLeft: 20,
    paddingTop: 10,
    marginRight: 5,
  },
  shopCart: {
    position: 'absolute',
    height: 25,
    width: 25,
    borderRadius: 15,
    backgroundColor: 'rgba(95,197,123,0.8)',
    right: 15,
    bottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
  },
  shopCartText: {
    color: 'white',
    fontWeight: 'bold',
  },
  mainBook: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 45,
    backgroundColor: '#fff',
  },
  subMainBook: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textBook: {fontSize: 20, fontWeight: 'bold', marginLeft: 15},
});
